In [ ]:
#  ASSIGNMENT - 01

In [2]:
# Transpose without function

m = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
ln = len(m)
col = len(m[0])
transpose = []
for i in range(col):
    row = []
    for j in range(ln):
        row.append(m[j][i])
    transpose.append(row)
print(transpose)

[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]


In [3]:
# Transpose without function

import numpy as np
m = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
transpose = np.transpose(m)
print(transpose)


[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [4]:
# assigning same element in different addresses

a = [1,2,3,4]
b = a[:]
c = a.copy()
print(id(a))
print(id(b))
print(id(c))

1854260914176
1854260914240
1854260914048


In [5]:
# Adding the temporary deleted elements

a = [1,2,3,4,5]
temp = a.pop()
print(a)
print(temp)
a.append(temp)
print(a)

[1, 2, 3, 4]
5
[1, 2, 3, 4, 5]
