In [ ]:
Numpy - Numerical Python 
      - It is a library used for handle numbers, arrays in efficient way.

In [4]:
import numpy as np

a = np.array([1,2,3,4,5])
a1 = np.array([[6,7,8,9],[10,11,12,13]])

print(a)
print(a1)

# printing dimension 
print(np.ndim(a))
print(np.ndim(a1))

print("Print 2nd index 3rd Value:",a1[1][2])

# Like range
print(np.arange(10)) # It is like regular range but used only in numpy, more optimized than range

# Printing row and column 
print(np.shape(a1))
print(np.shape(a))


[1 2 3 4 5]
[[ 6  7  8  9]
 [10 11 12 13]]
1
2
Print 2nd index 3rd Value: 12
[0 1 2 3 4 5 6 7 8 9]
(2, 4)
(5,)


In [104]:
import numpy as np

a1 = np.array([[1,2,3,4,5],[1,2,3,4,5],[3,4,5,6,7],[34,45,56,67,78]])
print(np.shape(a1))
print(np.ndim(a1))

(4, 5)
2


In [106]:
# 4D Arrays

import numpy as np
arr = np.ones((2,3,2,2))
print(arr) 
print(arr.ndim)

[[[[1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]]]


 [[[1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]]]]
4


In [107]:
# Time checking
L = range(1000)
%timeit a**2

780 ns ± 24.2 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [23]:
#  Mutability 

a = np.array([[1,2,3,4,5],[6,7,8,9,0]])

print(a)
print(a.ndim)
print(a.shape)
print(len(a))
print(a[1][2])
a[1] = 100
print(a[1][2])

[[1 2 3 4 5]
 [6 7 8 9 0]]
2
(2, 5)
2
8
100


In [27]:
ls = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[0,11,12]]])
print(ls)
print(ls.shape)
print(ls[0][1][0])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [ 0 11 12]]]
(2, 2, 3)
4


In [31]:
# Start, stop, step in arange

a = np.arange(2,10,2)
print(a)

[2 4 6 8]


In [34]:
# Linespace -> start, stop, No.of divisions it will divide value between start to stop in n part
ls = np.linspace(1,2,4)
print(ls)

[1.         1.33333333 1.66666667 2.        ]


In [36]:
# Common Arrays autofill like zfill in numpy is np.zeros

a = np.zeros((1,2))
print(a)

[[0. 0.]]


In [43]:
# To create 3D array, with diagonal value 1

a = np.eye(3)
print(a)
a = np.eye(4)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [45]:
a = np.diag([1**2, 2**2, 3**2, 4**2, 5**2])
print(a)
print(a.shape)

[[ 1  0  0  0  0]
 [ 0  4  0  0  0]
 [ 0  0  9  0  0]
 [ 0  0  0 16  0]
 [ 0  0  0  0 25]]
(5, 5)


In [91]:
from numpy import random
print(random.rand(3))

[0.64999855 0.43260495 0.19662394]


In [ ]:
Basic Datatype Conversion

In [49]:
a = np.arange(10)
a.dtype

dtype('int32')

In [50]:
# Complex Datatypes

d = np.array([1+2j,2+4j])
print(d.dtype)

complex128


In [54]:
# Boolean and unicode characters

d = np.array([True, True, False, True])
print(d.dtype)

s = np.array(["Sam","Jon"])
print(s.dtype)

bool
<U3


In [80]:
# SLICING AND INDEXING

a = np.arange(10)
a[5:] = 10
print(a)

[ 0  1  2  3  4 10 10 10 10 10]


In [63]:
a[1:9:2]

array([1, 3, 5, 7])

In [81]:
#  Assigning b array to a array's 5th index to 9th index.
b = np.arange(5)
a[5:] = b[::-1]
print(a)

[0 1 2 3 4 4 3 2 1 0]


In [82]:
b = np.arange(5)
a[5:] = b[::-1]
print(a)

[0 1 2 3 4 4 3 2 1 0]


In [83]:
#  COPIES AND VIEWS
a = np.arange(10)
b = a[::]
print(id(a))
print(id(b))


2439413741104
2439413735056


In [84]:
c = a[::2]
print(c)
print(id(c))

[0 2 4 6 8]
2439413736016


In [85]:
print(np.may_share_memory(a,b))

True


In [87]:
print(np.may_share_memory(b,c))

True


In [89]:
d = a
print(id(a))
print(id(b))
print(np.may_share_memory(a,d))

2439413741104
2439413735056
True


In [95]:
b[0] = 10
# d[0] = 10
print(b)
# print(d)
print(a)

[10  1  2  3  4  5  6  7  8  9]
[10  1  2  3  4  5  6  7  8  9]


In [97]:
a = np.arange(10)
c = a[::2].copy()
print(c)

[0 2 4 6 8]


In [98]:
c[0] = 10
print(c)
print(a)

[10  2  4  6  8]
[0 1 2 3 4 5 6 7 8 9]


In [103]:
a = np.arange(10)
c = a[::]
c[0] = 10
print(a)
print(c)

[10  1  2  3  4  5  6  7  8  9]
[10  1  2  3  4  5  6  7  8  9]
